function [fitresult, gof] = Data_Fit(j, i, ROI_array)
%CREATEFIT(J,I,ROI_ARRAY)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : j
%      Y Input : i
%      Z Output: ROI_array
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-Jan-2015 
%  Adapted by John Canty


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( j, i, ROI_array );

% Set up fittype and options. Fit to 2D Gaussian
% ft = 'linearinterp';
ft = fittype(@(a,b,c,d,x,y) a*exp(-((x-b).^2)/(2*d^2)-((y-c).^2)/(2*d^2)),'independent',{'x','y'},'dependent','z');

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, 'Normalize', 'off' );

% Plot fit with data.
figure();
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'ROI_array vs. j, i', 'Location', 'NorthEast' );
% Label axes
xlabel j
ylabel i
zlabel ROI_array
grid on
view( 176.5, 90.0 );


